### ISSUE TITLE
Matrix multiplication error, size mismatch

### ISSUE THREAD

**Issue by karanrampal** [vlukiyanov/pt-sdae#10]
This is my first time ever reporting anything. But shouldn't the val_batch also be reshaped and squeezed similar to training batch. Otherwise for MNIST I get "RuntimeError: The size of tensor a (784) must match the size of tensor b (28) at non-singleton dimension 3". After reshaping it works well.

validation_inputs.append(val_batch[0].squeeze(1).view(val_batch[0].size(0), -1))

https://github.com/vlukiyanov/pt-sdae/blob/7ba48ab4bfea1437b3c891b81a94c8226f3c78a3/ptsdae/model.py#L117

Thanks.

Best regards,
Karan

**Comment by vlukiyanov** [comment]
Hi,

I think that is a rogue debugging line I forgot to remove from the training batch code rather than something to add to the validation, as its more coherent to let the preprocessing handle transforming [batch_size, 28, 28] to [batch_size, 784], and leave the autoencoder to handle the natural input shape, which is [batch_size, 784]. 

For MNIST, I've used
`torch.ByteTensor(torch.ByteStorage.from_buffer(img.tobytes())).float()`  to process torchvision MNIST dataset (see examples).

The alternative, as you outline, would be to add the missing handling of 2D data to the validation stage.

Vlad

**Comment by vlukiyanov** [comment]
I'm going to merge this change, please reopen or PR if you feel it needs a different fix. 

Vlad

**Comment by karanrampal** [comment]
ok, i agree pre-processing should handle the reshaping. :+1:
